# Generated by Django 5.2.3 on 2025-07-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="projects/"),
        ),
        migrations.AlterField(
            model_name="projectscreenshot",
            name="image",
            field=models.ImageField(upload_to="project_screenshots/"),
        ),
    ]
